---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

## Create/Update the root user password
- name: Database | Update root password
  mysql_user:
      name: root
      host: "{{ item.host }}"
      check_implicit_admin: yes
      password: "{{ item.password }}"
      login_user: "{{ item.name }}"
      login_host: "{{ item.host }}"
      login_password: "{{ item.password }}"
  with_items: "{{ database_root }}"

## Create the databases
- name: Database | Create databases
  mysql_db:
      name: "{{ item[0].name }}"
      collation: "{{ item[0].collation }}"
      encoding: "{{ item[0].encoding }}"
      state: present
      login_user: "{{ item[1].name }}"
      login_host: "{{ item[0].host }}"
      login_password: "{{ item[1].password }}"
  with_nested:
      - "{{ databases }}"
      - "{{ database_root }}"

# Create users and give them privileges
- name: Database | Create users
  mysql_user:
      name: "{{ item[0].user }}"
      password: "{{ item[0].password }}"
      priv: "{{ item[0].database }}.*:ALL"
      state: present
      login_user: "{{ item[1].name }}"
      login_host: "{{ item[0].host }}"
      login_password: "{{ item[1].password }}"
  with_nested:
      - "{{ database_users }}"
      - "{{ database_root }}"